version: "3"

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge

services:

  postgis:
    build: "."
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PROJECT_DIR}:/opt/project
    networks:
      - postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    env_file: ./.env
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "127.0.0.1:8081:8081"
    links:
      - postgis:postgres  # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:${POSTGRES_PORT:-5432}/postgres?sslmode=disable
    depends_on:
      - postgis
    networks:
      - postgres