version: "3"

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge

services:

  postgis:
    build: "."
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PROJECT_DIR}:/opt/project
    networks:
      - postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    env_file: ./.env
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}