version: "3"

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge

services:

  postgis:
    build: "."
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PROJECT_DIR}/data:/opt/data
      - ${PROJECT_DIR}/${ACTIVE_MAPPING}:/opt/mapping.yaml
    networks:
      - postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    env_file: ./.env
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}